FROM ubuntu:14.04

WORKDIR /mxbuild
COPY mxnet-distro /mxbuild/mxnet-distro
COPY deps-lib/1404 /mxbuild/mxnet-distro/deps

COPY mxnet_build1404.sh /tmp
RUN chmod +x /tmp/mxnet_build1404.sh
RUN /tmp/mxnet_build1404.sh
RUN rm -f /tmp/mxnet_build1404.sh

